### ISSUE TITLE
Configurable tokens

### ISSUE THREAD

**Issue by rudiedirkx** [rudiedirkx/Query-stripper#2]
Install with a list of tokens:

```
atl_medium
atl_camp
atl_camptype
atl_source
utm_source
utm_medium
utm_term
utm_campaign
utm_content
utm_cid
utm_reader
ref_
aff_
mtrck
xtor
xtref
xtrck
```

but make them configurable.

How to update `logic.js`? Background script can load from `storage.local` once, but content script can't keep state...

**Comment by synthgab** [comment]
As far as I understand it, the main issue here is that the Chrome API is mainly asynchronous (send message,  storage.get, etc.), but we NEED to be synchronous by design ( and Google allows this with the « blocking » possibility of the « onBeforeRequest » event ) ...

**Comment by rudiedirkx** [comment]
Yes, storage is async, but the background script only needs to load it once, when loading itself. After that, the big script stays alive with the tokens cached. All requests after initial load will use the cached tokens. So bg script is fine. 

The content script doesn't have state, so it would have to load the tokens in EVERY request on EVERY page. That's huge for something rarely used. It's not super important, because it only handles history state changes via JS, but still...

**Comment by rudiedirkx** [comment]
Screw that. `chrome.storage.local` is cheap. I'm doing it.

**Comment by rudiedirkx** [comment]
I like it.
